apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: tensorflow-serving
    name: tensorflow-serving
  spec:
    ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    selector:
      io.kompose.service: tensorflow-serving
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: tensorflow-serving-seed-inception
  spec:
    template:
      metadata:
        name: seed-inception
      spec:
        containers:
        - name: seed
          image: bitnami/tensorflow-inception:latest
          command: ["/bin/sh"]
          args: ["-c", "curl -o /seed/inception-v3-2016-03-01.tar.gz http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz && \
                cd /seed/ && tar -xzf inception-v3-2016-03-01.tar.gz && \
                rm inception-v3-2016-03-01.tar.gz && \
                inception_saved_model --checkpoint_dir=/seed/inception-v3 --output_dir=/seed/ && \
                rm -rf inception-v3"]
          volumeMounts:
          - name: seed
            mountPath: /seed
        restartPolicy: Never
        volumes:
        - name: seed
          persistentVolumeClaim:
            claimName: tensorflow-serving-seed-inception
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: tensorflow-serving
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: tensorflow-serving
      spec:
        containers:
        - image: bitnami/tensorflow-serving:latest
          name: tensorflow-serving
          ports:
          - containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/tensorflow-serving
            name: bitnamidockertensorflowinception-tensorflow-serving-data
          - mountPath: /bitnami/model-data
            name: tensorflow-serving-seed-inception
        restartPolicy: Always
        volumes:
        - name: bitnamidockertensorflowinception-tensorflow-serving-data
          persistentVolumeClaim:
            claimName: bitnamidockertensorflowinception-tensorflow-serving-data
        - name: tensorflow-serving-seed-inception
          persistentVolumeClaim:
            claimName: tensorflow-serving-seed-inception
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: bitnamidockertensorflowinception-tensorflow-serving-data
    name: bitnamidockertensorflowinception-tensorflow-serving-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: tensorflow-serving-seed-inception
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}
